version: '3.8'

services:
  pgvector:
    image: ankane/pgvector:latest
    container_name: pgvector
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=ginitoru
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
