apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector-deployment
spec:
  selector:
    matchLabels:
      app: pgvector
  template:
      metadata:
        labels:
          app: pgvector
      spec:
        containers:
          - name: pgvector
            image: ankane/pgvector:latest
            env:
              - name: POSTGRES_DB
                value: 'vectordb'
              - name: POSTGRES_USER
                value: 'ginitoru'
              - name: POSTGRES_PASSWORD
                value: '1234'
            ports:
              - containerPort: 5432
            volumeMounts:
              - name: pgvector-persistent-storage
                mountPath: /var/lib/postgresql/data
        volumes:
          - name: pgvector-persistent-storage
            persistentVolumeClaim:
              claimName: pgvector-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: pgvector-service
spec:
  ports:
    - protocol: 'TCP'
      port: 5432
      targetPort: 5432
  selector:
    app: pgvector
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgvector-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

