server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true

spring:
  application:
    name: ai-core
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/vectordb
    username: ${DB_USERNAME:ginitoru}
    password: ${DB_PASSWORD:1234}

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 4096

  web:
    resources:
      static-locations: classpath:/static/browser
